name: torch
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - ipykernel
  - pip
  - pip:
      - ultralytics
      - streamlink
      - streamlit
      - python-dotenv
      - openai
      - loguru
      - supervision
      - transformers
